### ISSUE TITLE
There is a problem with http request when running exe file. 

### ISSUE THREAD

**Issue by li9527yu** [Priyavrat13/MDAT#1]
![89c8da185fa86b105d2e7871559660f](https://github.com/Priyavrat13/MDAT/assets/54931794/cb54d592-73de-4bc7-a232-f311a8bfaf57)

Recently, I am looking for a annotation system for multi-modal tweets, your code can provide me with a lot of help. If possible, I hope you can share your open source code with me

**Comment by li9527yu** [comment]
> ![89c8da185fa86b105d2e7871559660f](https://private-user-images.githubusercontent.com/54931794/296928063-cb54d592-73de-4bc7-a232-f311a8bfaf57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzc5ODEsIm5iZiI6MTcwNTM3NzY4MSwicGF0aCI6Ii81NDkzMTc5NC8yOTY5MjgwNjMtY2I1NGQ1OTItNzNkZS00YmM3LWEyMzItZjMxMWE4YmZhZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0MDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOGNjZTJmYjFmN2E1MzZhMDQzOTAyNmIyZmMwYjE4MmZkZmFkYzBiMTRmZmE5MTAzMDAxYTY5OTMzZWUwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5hWY9hkFkbENVDc-j2DblWxZGVUPfsBZA6KPzNRlYMc)
> 
> Recently, I am looking for a annotation system for multi-modal tweets, your code can provide me with a lot of help. If possible, I hope you can share your open source code with me
My email address is 2770404066lzy@gamil.com ,Hope to get your reply as soon as possible, I wish you a happy life

**Comment by Priyavrat13** [comment]
@li9527yu try to install it as per instructions provided in readme file. Your Internet should be connected

**Comment by Priyavrat13** [comment]
Dear @li9527yu I hope the tool is working fine now at your end.
